### ISSUE TITLE
How to run in server mode?

### ISSUE THREAD

**Issue by rafis** [wilkenstein/redis-mock-js#13]
How to run in server mode like Happy DB?

```
var redisJs = require('redis-js');
var redisServer = redisJs.createServer();
redisServer.listen(6739);
```

**Comment by wilkenstein** [comment]
Server mode is unsupported right now. There are 2 issues:
1. we don't have an implementation of redis's communication protocol, RESP, so external redis clients, e.g., `node-redis`, couldn't talk to the server;
2. there is no great cross-JS-engine way to bind to a port that I know of.

1 is just a matter of implementing http://redis.io/topics/protocol. 2 is more difficult since it requires different code paths. Unless you know of a good way in javascript!

**Comment by wilkenstein** [comment]
`1.1.0` is the release slated for server support. If server support is important for you, we could look at moving that up.

**Comment by rafis** [comment]
I haven't noticed the header **Roadmap**, I thought it already been implemented.
